### PR TITLE
minimal update to Python 3; add "list of closest DCs" as well as "the closest" to outputs

### PR DESCRIPTION
**Pull request by rpardini**
- Hammer until works under Python 3 (not an expert, by far)
- Using the same logic to calculate "the closest DC", also calculate a comma-separated ordered list of "closest DCs"

This should be useful for people who don't have presence in all possible DC's, that way you can use the 2nd or 3rd closest if that's all you can afford ;-)

### CODE REVIEW

**Comment by JedMeister** [comment]
Hi @rpardini - Thanks so much for your contribution. I've had a quick glance and it looks good to me. However, I will ask my colleague @Ongle to do a proper review. He won't be working again until next week, but hopefully we can at least get you some proper feedback soon, if not just merge.

**Comment by OnGle** [comment]
I'll actually be about tomorrow too, so if time allows I'll do a review then if not then by monday. Just had a quick glance and it looks good though!

**Comment by JedMeister** [comment]
Actually, if you get a chance @Christie018, perhaps you could review this PR too?

**Review by Christie018 — APPROVED** [review]
The changes appear to update the aws datacenters mapping code. My input would be to try a sandboxed version of this code and make sure it works correctly to generate the visual map and integrates with turnkey hub and the TKLBAM mechanism.

**Review by OnGle — APPROVED** [review]
I can't/wont comment on the aws data, I'm not knowledgeable enough in that area to do so.

As far as the code goes, this is perfectly acceptable. The python3 update is mostly a direct translation from 2->3, that unfortunately means no context managers and no f-strings, but doing it in this manner makes it unlikely any new bugs made it in due to subtly different behavior of more modern python practices.

**Comment by Christie018** [comment]
Figured that's what some of the slight code modifications  were pointing towards. I agree, the new PR doesn't appear to cause any new bugs as you noted.

**Pull request merged**
